const ACTIONS_TYPES = {
    GET_BLOCKS: 'GET_BLOCKS',
    GET_BLOCKS_RECEIVED: 'GET_BLOCKS_RECEIVED',
    GET_TRAPS: 'GET_TRAPS',
    GET_TRAPS_RECEIVED: 'GET_TRAPS_RECEIVED'
  }
  export default ACTIONS_TYPES